- name: Install grid and pool account setting
  hosts: localhost
  connection: local 
  vars_files:
    - vars/main.yml
  roles:
    - role: geerlingguy.repo-epel
    - role: geonmo.grid
      grid_middleware: "OSG"
      grid_dummy_host_certificate: true
      grid_dummy_ca:
        crt: "{{ ca_info.caname }}.crt"
        key: "{{ ca_info.caname }}.key"
        hash: 19d25ae9
        cn: /C=KR/O=KISTI/O=GSDC/O=Dummy CA/CN=
      ca_info:
        caname: "CA"
        cn: /C=KR/O=KISTI/O=GSDC/CN=Dummy CA
        target: /C=KR/O=KISTI/O=GSDC/*
